# Config Aliases
alias Hypr='cd ~/.config/hypr'
alias Fish='cd ~/.config/fish'
alias Kitty='cd ~/.config/kitty'
alias Nvim='cd ~/.config/nvim'
alias Waybar='cd ~/.config/waybar'
alias Fastfetch='cd ~/.config/fastfetch'
alias Niri='cd ~/.config/niri'
alias Ags='cd ~/.config/ags'
alias WayEdges='cd ~/.config/way-edges'

# Personal Aliases
alias Documents='cd ~/Documents'
alias Downloads='cd ~/Downloads'
alias Assets='cd ~/Documents/Assets'

# Programming Aliases
alias Programming='cd ~/Documents/Programming'
alias Go='cd ~/Documents/Programming/Go'
alias Jupyter='cd ~/Documents/Programming/Jupyter'
alias Rust='cd ~/Documents/Programming/Rust'
alias Bash='cd ~/Documents/Programming/Bash'
alias Python='cd ~/Documents/Programming/Python'
alias Fortran='cd ~/Documents/Programming/Fortran'
alias C='cd ~/Documents/Programming/C'
alias C++='cd ~/Documents/Programming/C++'
alias Java='cd ~/Documents/Programming/Java'
alias JavaS='cd ~/Documents/Programming/JavaScript'
alias TypeS='cd ~/Documents/Programming/TypeScript'
alias Wolfram='cd ~/Documents/Programming/Wolfram\ Mathematica'
alias Lua='cd ~/Documents/Programming/Lua'
alias ASM='cd ~/Documents/Programming/ASM'
alias Swift='cd ~/Documents/Programming/Swift'
alias Lean4='cd ~/Documents/Programming/Lean4'
alias Ruby='cd ~/Documents/Programming/Ruby'
